import { useEffect, useRef, useState } from 'react'
import mermaid from 'mermaid'
import { FigureCaption } from './FigureCaption'

interface MermaidBlockProps {
  code: string
  figureNumber: number
}

export function MermaidBlock({ code, figureNumber }: MermaidBlockProps) {
  const svgContainerRef = useRef<HTMLDivElement>(null)
  const [svg, setSvg] = useState<string>('')
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    const renderDiagram = async () => {
      if (!svgContainerRef.current) return

      try {
        const id = `mermaid-${figureNumber}`
        const result = await mermaid.render(id, code)
        setSvg(result.svg)
        setError(null)
      } catch (err) {
        setError(err instanceof Error ? err.message : 'Failed to render diagram')
        setSvg('')
      }
    }

    renderDiagram()
  }, [code, figureNumber])

  if (error) {
    return (
      <figure
        data-mermaid
        data-figure={figureNumber}
        className="border border-hair border-ink3 p-card mb-card bg-paper"
      >
        <div className="font-mono text-meta text-warn mb-snug">Diagram error</div>
        <pre className="font-mono text-bodysm text-warn">{error}</pre>
        <FigureCaption figureNumber={figureNumber} />
      </figure>
    )
  }

  return (
    <figure
      data-mermaid
      data-figure={figureNumber}
      className="border border-hair border-ink3 p-card mb-card bg-card"
    >
      <div
        ref={svgContainerRef}
        // biome-ignore lint/security/noDangerouslySetInnerHtml: Mermaid SVG is safe, generated by mermaid library
        dangerouslySetInnerHTML={{ __html: svg }}
        className="mb-snug overflow-x-auto"
      />
      <FigureCaption figureNumber={figureNumber} />
    </figure>
  )
}
